trigger: 
- master

parameters:
  - name: environment
    type: string
    default: 'dev'
    values:
      - "dev"
      - "qa"


pool:
  name: Nariyao
  demands:
    - os -equals ubuntu-22.04

name: AzureDevOps-testing-pipeline-${{ parameters.environment }}

# Power BI Actions: Publishs
jobs:
- job: power_bi_actions
  displayName: Power BI Actions
  variables:
    POWER_BI_CLIENT_ID: "testing-client-id"
    POWER_BI_CLIENT_SECRET: "testing-client-secret"
  steps:
  - checkout: self
  - script: |
      echo "working directory: $(Build.SourcesDirectory)/devops/scripts"
    displayName: 'Show working directory'

    # Power BI publish report
  - script: |
      python3 -c "
      from main import PowerBIActions
      power_bi = PowerBIActions(env='dev')
      power_bi.publish_report('reports')
      "
    env:
      POWER_BI_CLIENT_ID: $(POWER_BI_CLIENT_ID)
      POWER_BI_CLIENT_SECRET: $(POWER_BI_CLIENT_SECRET)
    workingDirectory: $(Build.SourcesDirectory)/devops/scripts
    displayName: 'Publish Power BI Reports'

    # Power BI Actions: Take over
  - script: |
      python3 -c "
      from main import PowerBIActions
      power_bi = PowerBIActions(env='dev')
      power_bi.take_ownership('1', 'new_owner@example.com')
      "
    workingDirectory: $(Build.SourcesDirectory)/devops/scripts
    displayName: "Take over reports"

    # Power BI Actions: Update parameters
  - script: |
      python3 -c "
      from main import PowerBIActions
      power_bi = PowerBIActions(env='dev')
      power_bi.update_parameters()
      "
    workingDirectory: $(Build.SourcesDirectory)/devops/scripts
    displayName: 'Update parameters'

    # Power BI Actions: Update gateways
  - script: |
      python3 -c "
      from main import PowerBIActions
      power_bi = PowerBIActions(env='dev')
      power_bi.update_gateways()
      "
    workingDirectory: $(Build.SourcesDirectory)/devops/scripts
    displayName: 'Update gateways'

    # Power BI Actions: Binding to gateways
  - script: |
      python3 -c "
      from main import PowerBIActions
      power_bi = PowerBIActions(env='dev')
      power_bi.binding_to_gateways()
      "
    workingDirectory: $(Build.SourcesDirectory)/devops/scripts
    displayName: 'Binding to gateways'
  
  # Power BI Actions: Publishs Paginated Reports
  - script: |
      python3 -c "
      from main import PowerBIActions
      power_bi = PowerBIActions(env='dev')
      power_bi.publish_paginated_report()
      "
    workingDirectory: $(Build.SourcesDirectory)/devops/scripts
    displayName: 'Publish Paginated Reports'